// Phone: walk to the ambulance, tap ✋ to get in, drive with the joystick, 🚨 siren, 🚪 out.
import puppeteer, { KnownDevices } from 'puppeteer-core';
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--enable-unsafe-swiftshader', '--use-angle=swiftshader'] });
const page = await browser.newPage();
await page.emulate(KnownDevices['iPhone 13 landscape']);
await page.goto(process.env.BASE ?? 'http://localhost:8765/', { waitUntil: 'networkidle0', timeout: 180000 });
await page.waitForFunction(() => !document.getElementById('start').disabled, { timeout: 60000 });
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const tap = async (sel) => { const b = await (await page.$(sel)).boundingBox(); await page.touchscreen.tap(b.x + b.width / 2, b.y + b.height / 2); };
console.log('loaded');
await tap('#start');
await wait(800);
await page.evaluate(() => { const a = __game.ambulance; __game.player.pos.copy(a.doorPoint); });
await wait(600);
await page.screenshot({ path: '.shots/drive-mobile-0-before.png' });
await tap('#btn-action');
await wait(1500);
await page.screenshot({ path: '.shots/drive-mobile-1-in.png' });
const r = { in: await page.evaluate(() => __game.ambulance.driving), buttons: await page.evaluate(() => [document.getElementById('btn-action').textContent, document.getElementById('btn-jump').textContent]) };
console.log('in', JSON.stringify(r));
const p0 = await page.evaluate(() => __game.ambulance.pos.toArray());
const st = await (await page.$('#stick')).boundingBox();
await page.touchscreen.touchStart(st.x + st.width / 2, st.y + st.height / 2);
await page.touchscreen.touchMove(st.x + st.width / 2, st.y + 4);
await wait(3000);
await page.screenshot({ path: '.shots/drive-mobile.png' });
console.log('cam', await page.evaluate(() => JSON.stringify({ cam: __game.follow.camera.position.toArray(), yaw: __game.input.yaw, pitch: __game.input.pitch, dist: __game.input.distance, amb: __game.ambulance.pos.toArray(), heading: __game.ambulance.heading, speed: __game.ambulance.speed })));
await page.touchscreen.touchEnd();
console.log('drove');
const p1 = await page.evaluate(() => __game.ambulance.pos.toArray());
r.drove = +Math.hypot(p1[0] - p0[0], p1[2] - p0[2]).toFixed(2);
await tap('#btn-jump');
await wait(300);
r.siren = await page.evaluate(() => __game.ambulance.siren);
await page.evaluate(() => { __game.ambulance.speed = 0; });
await wait(300);
await tap('#btn-action');
await wait(400);
r.out = await page.evaluate(() => !__game.ambulance.driving && __game.player.rig.root.visible);
await wait(1000);
await page.screenshot({ path: '.shots/drive-mobile-3-out.png' });
console.log(JSON.stringify(r));
await browser.close();
