// Wolfson Harbor: drive Downtown's avenue south down Harbor Road to the quay; the jetty is dry, the sea isn't.
import puppeteer from 'puppeteer-core';
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--enable-unsafe-swiftshader', '--use-angle=swiftshader'], defaultViewport: { width: 1280, height: 720 }, protocolTimeout: 240000 });
const page = await browser.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(String(e)));
page.on('console', (m) => m.type() === 'error' && errors.push(m.text()));
await page.goto(process.env.BASE ?? 'http://localhost:8765/', { waitUntil: 'networkidle0', timeout: 180000 });
await page.waitForFunction(() => !document.getElementById('start').disabled, { timeout: 120000 });
await page.click('#start');
const g = (fn, a) => page.evaluate(fn, a);
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const drive = (throttle, steer, seconds) => g(([throttle, steer, seconds]) => {
  const { ambulance } = __game;
  for (let i = 0; i < seconds * 60; i++) ambulance.update(1 / 60, i / 60, { throttle, steer });
  return { pos: ambulance.pos.toArray().map((v) => +v.toFixed(1)), speed: +ambulance.speed.toFixed(1) };
}, [throttle, steer, seconds]);
const r = {};
await g(() => { const a = __game.ambulance; a.pos.set(-111.5, 0, 20); a.heading = 0; a.update(1 / 60, 0, {}); a.syncTransform(); __game.player.pos.copy(a.doorPoint); });
await wait(800);
await page.keyboard.press('KeyE');
await page.waitForFunction(() => __game.ambulance.driving, { timeout: 15000 }).catch(() => {});
r.driving = await g(() => __game.ambulance.driving);
r.harborRoad = await drive(1, 0, 6);
r.name1 = await g(() => __game.world.locationName(__game.ambulance.pos));
r.toQuay = await drive(1, 0, 4);
r.name2 = await g(() => __game.world.locationName(__game.ambulance.pos));
await drive(-1, 0, 1.5); await drive(0, 0, 2);
await page.keyboard.press('KeyE');
await wait(1500);
r.out = await g(() => !__game.ambulance.driving);
r.jettyDry = await g(() => !__game.world.inWater(-101, 130));
r.seaWet = await g(() => __game.world.inWater(-110, 130));
await g(() => { __game.player.pos.set(-101, 0, 132); __game.input.yaw = 0.3; __game.input.distance = 10; __game.input.pitch = 0.25; });
await wait(2500);
r.name3 = await g(() => document.getElementById('location').textContent);
await page.screenshot({ path: '.shots/harbor-1-jetty.png' });
await g(() => { __game.player.pos.set(-160, 0, 106); __game.input.yaw = 2.6; __game.input.distance = 12; __game.input.pitch = 0.3; });
await wait(2500);
await page.screenshot({ path: '.shots/harbor-2-yard.png' });
await g(() => { __game.bigMap.toggle(true); __game.bigMap.zoom = 2.4; __game.bigMap.center = { x: -146, z: 85 }; __game.bigMap.draw(); });
await wait(800);
await page.screenshot({ path: '.shots/harbor-3-map.png' });
console.log(JSON.stringify(r, null, 1));
console.log('ERRORS:', errors.length ? errors : 'none');
await browser.close();
