// Phones in portrait: after Start shift a "turn sideways" card pauses the game; rotating (or skipping) clears it.
import puppeteer, { KnownDevices } from 'puppeteer-core';
const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new', args: ['--enable-unsafe-swiftshader', '--use-angle=swiftshader'], protocolTimeout: 240000 });
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const errors = [];
const page = await browser.newPage();
page.on('pageerror', (e) => errors.push(String(e)));
await page.emulate(KnownDevices['iPhone 13']);
await page.goto(process.env.BASE ?? 'http://localhost:8765/', { waitUntil: 'networkidle0', timeout: 180000 });
await page.waitForFunction(() => !document.getElementById('start').disabled, { timeout: 120000 });
const vis = () => page.evaluate(() => !document.getElementById('rotate').classList.contains('hidden'));
const r = { beforeStart: await vis() };
await page.tap('#start');
await wait(800);
r.portraitAfterStart = await vis();
r.ios = await page.evaluate(() => document.getElementById('rotate').classList.contains('ios'));
const t0 = await page.evaluate(() => __game.missions.time);
await wait(1500);
r.pausedWhileCard = (await page.evaluate(() => __game.missions.time)) === t0;
await page.screenshot({ path: '.shots/rotate-portrait.png' });
await page.emulate(KnownDevices['iPhone 13 landscape']);
await wait(1200);
r.landscape = await vis();
await page.screenshot({ path: '.shots/rotate-landscape.png' });
await page.emulate(KnownDevices['iPhone 13']);
await wait(800);
r.backToPortrait = await vis();
await page.tap('#rotate-skip');
await wait(500);
r.afterSkip = await vis();
console.log(JSON.stringify(r));
console.log('ERRORS:', errors.length ? errors : 'none');
await browser.close();
